name: USA Traffic Autopilot  
on:  
  schedule:  
    - cron: '0 */4 * * *' # Every 4 hours  
  workflow_dispatch:  

concurrency:  
  group: usa-traffic  
  cancel-in-progress: true  

jobs:  
  traffic:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Google Index Boost  
        run: |  
          curl -X POST "https://index.googleapis.com/v3/urlNotifications:publish" \  
          -H "Content-Type: application/json" \  
          -d '{"url": "https://gategith.github.io/usa-cash-algeria/", "type": "URL_UPDATED"}'  

      - name: Reddit Blast  
        run: |  
          curl -X POST "https://www.reddit.com/api/submit" \  
          -H "User-Agent: usa-cash/1.0" \  
          -d 'title=EXCLUSIVE: 20% Walmart+ Cashback (US Only)&sr=deals&url=https://gategith.github.io/usa-cash-algeria/'  
