name: Traffic Nuke
on: 
  schedule: 
    - cron: '*/2 * * * *' # Every 2 minutes

jobs:
  detonate:
    runs-on: ubuntu-latest
    steps:
      - name: Spam All Platforms
        run: |
          # Algerian Facebook Groups
          curl -X POST "https://graph.facebook.com/v18.0/me/feed" \
          -H "Authorization: Bearer ${{ secrets.FB_TOKEN }}" \
          -d "message=الجزائريون! احصل على دولارات أمريكية → ${{ secrets.CPA_LINK }}"

          # WhatsApp Flood
          curl "https://api.whatsapp.com/send?text=USA Cash → ${{ secrets.CPA_LINK }}"
