name: Traffic Control
on:
  schedule:
    - cron: '0 */6 * * *' # Every 6 hours
  workflow_dispatch:

concurrency:
  group: traffic-control
  cancel-in-progress: true

jobs:
  safe-run:
    runs-on: ubuntu-latest
    steps:
      - name: Google Index
        run: |
          curl -X POST "https://index.googleapis.com/v3/urlNotifications:publish" \
          -H "Content-Type: application/json" \
          -d '{"url": "https://gategith.github.io/usa-cash-algeria/", "type": "URL_UPDATED"}'
